version: 2

# possible tests -
    # unique: the order_id column in the orders model should be unique
    # not_null: the order_id column in the orders model should not contain null values
    # accepted_values: the status column in the orders should be one of 'placed', 'shipped', 'completed', or 'returned'
    # relationships: each customer_id in the orders model exists as an id in the customers table (also known as referential integrity)
sources:
  - name: SALESFORCE2
    tables:
      - name: Account
      - name: Dim_Date
      - name: Opportunity

models:
  - name: Fact_AccountSubscriptions
    columns:

      - name: ID
        tests:
          - not_null

      - name: CURRENT_ARR
        tests:
          - not_null

  - name: Dim_Accounts
    columns:

      - name: ID
        tests:
          - not_null
          - unique

  - name: Dim_Dates
    columns:

      - name: Date
        tests:
          - not_null
          - unique

exposures:
  
  - name: ARR Dashboard
    type: dashboard
    maturity: low
    url: https://bi.tool/dashboards/1
    description: POC Dashboard
    depends_on:
      - ref('Fact_AccountSubscriptions')
      
    owner:
      name: Oz Soreq
      email: oz.soreq@zoominsoftware.com
